### ISSUE TITLE
Use of httplib2 assumes write access to CWD

### ISSUE THREAD

**Issue by mikebdotorg** [rfverbruggen/rachiopy#8]
`__init__.py` contains:

```_HTTP = httplib2.Http('.cache')```

This fails if the code is executed from a working directory the user does not have permission to write.

In my specific use case - homeassistant is executing from systemd with a working directory of / and /.cache is not writable.

```hass[22572]: 2017-08-06 20:32:30 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform rachio
hass[22572]: Traceback (most recent call last):
hass[22572]: File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 164, in _async_setup_platform
hass[22572]: SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
hass[22572]: File "/usr/lib/python3.4/asyncio/tasks.py", line 372, in wait_for
hass[22572]: return fut.result()
hass[22572]: File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
hass[22572]: raise self._exception
hass[22572]: File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
hass[22572]: result = self.fn(*self.args, **self.kwargs)
hass[22572]: File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/switch/rachio.py", line 42, in setup_platform
hass[22572]: from rachiopy import Rachio
hass[22572]: File "/srv/homeassistant/lib/python3.4/site-packages/rachiopy/__init__.py", line 14, in <module>
hass[22572]: _HTTP = httplib2.Http('.cache')
hass[22572]: File "/srv/homeassistant/lib/python3.4/site-packages/httplib2/__init__.py", line 915, in __init__
hass[22572]: self.cache = FileCache(cache)
hass[22572]: File "/srv/homeassistant/lib/python3.4/site-packages/httplib2/__init__.py", line 675, in __init__
hass[22572]: os.makedirs(self.cache)
hass[22572]: File "/usr/lib/python3.4/os.py", line 237, in makedirs
hass[22572]: mkdir(name, mode)
hass[22572]: PermissionError: [Errno 13] Permission denied: '.cache'
```

Please update to consider checking the location prior to calling http2lib AND using a more explicit location like TMPDIR or other.

I got past it for now by just changing .cache to `_HTTP = httplib2.Http('/tmp/.rachiopy-cache')`

Thanks!

**Comment by challlen** [comment]
Ran into this issue too. The suggested fix proposed above worked.

**Comment by rfverbruggen** [comment]
I'm currently investigating this issue. It seems the Rachio API doesn't allow caching so it could be delete completely. As soon as I can confirm this I will create the solution and update the package.

**Comment by rfverbruggen** [comment]
I created a new release. It is published to https://pypi.org/project/RachioPy/0.1.3/.

Could you please confirm it's working and close the issue: @mikebdotorg and @challlen

**Comment by tiszavolgyi** [comment]
It did not solve the issue for me. I did the following:

```
(homeassistant) homeassistant@Marvin:~$ pip3 install RachioPy==0.1.3 
Collecting RachioPy==0.1.3
  Downloading RachioPy-0.1.3.tar.gz
Requirement already satisfied: httplib2 in /srv/homeassistant/lib/python3.6/site-packages (from RachioPy==0.1.3)
Building wheels for collected packages: RachioPy
  Running setup.py bdist_wheel for RachioPy ... done
  Stored in directory: /home/homeassistant/.cache/pip/wheels/6d/4d/e7/bccea734452de382efffe93f021588930caf7b0ed62eb8cab7
Successfully built RachioPy
Installing collected packages: RachioPy
  Found existing installation: RachioPy 0.1.2
    Uninstalling RachioPy-0.1.2:
      Successfully uninstalled RachioPy-0.1.2
```
Then restarted HA and still having the same issue (I am running HA in Virtual env under Ubuntu, also gave hoeassistant:hoeassistant user:group to the user/.cache folder):

Log Details (ERROR)
```

Tue Feb 20 2018 17:19:44 GMT-0800 (PST)

Error while setting up platform rachio

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 84, in async_setup
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/switch/rachio.py", line 39, in setup_platform
    from rachiopy import Rachio
  File "/srv/homeassistant/lib/python3.6/site-packages/rachiopy/__init__.py", line 14, in <module>
    _HTTP = httplib2.Http('.cache')
  File "/srv/homeassistant/lib/python3.6/site-packages/httplib2/__init__.py", line 915, in __init__
    self.cache = FileCache(cache)
  File "/srv/homeassistant/lib/python3.6/site-packages/httplib2/__init__.py", line 675, in __init__
    os.makedirs(self.cache)
  File "/srv/homeassistant/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '.cache'
```

**Comment by tiszavolgyi** [comment]
I've solved it by adding 'WorkingDirectory' parameter to the home-assistant@pi.service file under /etc/systemd/system as show below:
```

[Unit]
Description=Home Assistant
After=network.target

[Service]
WorkingDirectory=/home/homeassistant
Type=simple
User=homeassistant
#make sure the virtualenv python binary is used
Environment=VIRTUAL_ENV="/srv/homeassistant"
Environment=PATH="$VIRTUAL_ENV/bin:$PATH"
ExecStart=/srv/homeassistant/bin/hass -c "/home/homeassistant/.homeassistant"

[Install]
WantedBy=multi-user.target
```

**Comment by rfverbruggen** [comment]
@tiszavolgyi as you can see in the trace that you are posting there is still the _HTTP = httplib2.Http('.cache') code that was part of rachiopy 0.1.2.

This is because Home-assistant is using the 0.1.2 version as you can see in: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/switch/rachio.py

The solution you are mentioning is working in the 0.1.2 version because you add the home directory. For this to work out of the box with 0.1.3 Home assistant should be updated.

The problem you are now experiencing is not a Rachiopy issue but one in Home assistant.

**Comment by mikebdotorg** [comment]
@tiszavolgyi -

Change lib/python3.5/site-packages/homeassistant/components/switch/rachio.py

To read
`REQUIREMENTS = ['rachiopy==0.1.3']`

I also added the WorkingDirectory you suggested, good idea for future proofing other components.

@rfverbruggen - this looks like it worked.

Closing bug.
